stages:
  data_ingestion:
    cmd : python src/datas/data_ingestion.py
    params : 
      - data_ingestion.test_size
    deps : 
      - src/datas/data_ingestion.py
    outs : 
      - data/raw
  
  data_preprocessing:
    cmd : python src/datas/data_preprocessing.py
    deps :
      - src/datas/data_preprocessing.py
      - data/raw
    outs :
      - data/interim

  feature_engineering:
    cmd : python src/features/feature_engineering.py
    deps :
      - src/features/feature_engineering.py
      - data/interim
    outs :
      - data/processed

  model_building:
    cmd : python src/model/model_building.py
    params :
      - model_building.n_estimators
    deps :
      - src/model/model_building.py
      - data/processed
    outs :
      - models

  model_evaluation:
    cmd : python src/model/model_evaluation.py
    deps :
      - src/model/model_evaluation.py
      - data/processed
      - models
    metrics :
      - reports/metrics.json
