name: ci_workflow

on: push

jobs:
  run_dvc_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@v3

      - name: python setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

        # chaching
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: install dependencies
        run: |
          pip install -r requirements.txt

      - name: run pipeline
        env:
          DAGSHUB_PAT: ${{secrets.DAGSHUB_PAT}}
        run: |
          dvc repro
      
      - name: run model test
        env:
          DAGSHUB_PAT: ${{secrets.DAGSHUB_PAT}}
        run: |
          python -m unittest tests/test_model.py
      
      - name: model promotion to production
        if: success()
      
        env:
          DAGSHUB_PAT: ${{secrets.DAGSHUB_PAT}}

        run: |
          python scripts/model_promotion.py

      - name: model load from registry
        if: success()
        env:
          DAGSHUB_PAT: ${{secrets.DAGSHUB_PAT}}
        run: |
          python scripts/load_model.py
        
      - name: Run Api Test
        env:
          DAGSHUB_PAT: ${{secrets.DAGSHUB_PAT}}
        
        run: |
          export PYTHONPATH=$PWD
          pytest tests/test_api_app.py tests/test_preprocessing.py
      
      - name: login to dockerhub
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME1}}
          password: ${{secrets.DOCKER_HUB_ACESS_TOKEN1}}

      - name: build docker image
        if: success()
        run: |
          docker build -t ${{secrets.DOCKER_HUB_USERNAME1}}/emotion_analysis:v1.1 .
        
      - name: push docker image to docker hub
        if: success()
        run: |
          docker push ${{secrets.DOCKER_HUB_USERNAME1}}/emotion_analysis:v1.1
          


        