name: ci_workflow

on: push

jobs:
  run_dvc_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@v3

      - name: python setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

        # chaching
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: install dependencies
        run: |
          pip install -r requirements.txt

      - name: run pipeline
        env:
          DAGSHUB_PAT: ${{secrets.DAGSHUB_PAT}}
        run: |
          dvc repro
      
      - name: run model test
        env:
          DAGSHUB_PAT: ${{secrets.DAGSHUB_PAT}}
        run: |
          python -m unittest tests/test_model.py
      
      - name: model promotion to production
        if: success()
      
        env:
          DAGSHUB_PAT: ${{secrets.DAGSHUB_PAT}}

        run: |
          python scripts/model_promotion.py
        
      - name: Run Api Test
        env:
          DAGSHUB_PAT: ${{secrets.DAGSHUB_PAT}}
        
        run: |
          export PYTHONPATH=$PWD
          python -m nltk.downloader stopwords wordnet
          pytest tests/test_api_app.py tests/test_preprocessing.py

      - name: Login to aws ECR
        run: |
          aws configure set aws_acess_key_id ${{secrets.EC2_SECRET_KEY}}
          aws configure set aws_secret_key_id ${{secrets.EC2_ACESS_KEY}}
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 128529977235.dkr.ecr.eu-north-1.amazonaws.com
      
      - name: Build docker image
        run: |
          docker build -t emotion_analysis_ecr .
        
      - name: Tag Docker image
        run: |
          docker tag emotion_analysis_ecr:latest 128529977235.dkr.ecr.eu-north-1.amazonaws.com/emotion_analysis_ecr:v1.2
      
      - name: 
        run: |
          docker push 128529977235.dkr.ecr.eu-north-1.amazonaws.com/emotion_analysis_ecr:v1.2
      
      # - name: login to dockerhub
      #   if: success()
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{secrets.DOCKER_HUB_USERNAME1}}
      #     password: ${{secrets.DOCKER_HUB_ACESS_TOKEN1}}

      # - name: build docker image
      #   if: success()
      #   run: |
      #     docker build -t ${{secrets.DOCKER_HUB_USERNAME1}}/emotion_analysis:v2.1 .
        
      # - name: push docker image to docker hub
      #   if: success()
      #   run: |
      #     docker push ${{secrets.DOCKER_HUB_USERNAME1}}/emotion_analysis:v2.1

      - name: Deploy to EC2
        if: success()
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USER}}
          key: ${{secrets.EC2_SSH_KEY}}
          script: |
            docker pull ${{secrets.DOCKER_HUB_USERNAME1}}/emotion_analysis:v2.1
            docker stop my-app || true
            docker rm my-app || true
            docker run -d -p 80:8000 --name my-app ${{secrets.DOCKER_HUB_USERNAME1}}/emotion_analysis:v2.1



        